// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfEvent struct {
	_        structs.HostLayout
	Comm     [16]uint8
	Buf      [256]uint8
	TotalLen int64
	ChunkLen int64
	ChunkIdx uint32
	Type     uint32
	Tgid     uint32
	Pid      uint32
	Saddr    uint32
	Daddr    uint32
	Sport    uint16
	Dport    uint16
	_        [4]byte
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	TcpRecvmsgFexit          *ebpf.ProgramSpec `ebpf:"tcp_recvmsg_fexit"`
	TcpSendmsgFexit          *ebpf.ProgramSpec `ebpf:"tcp_sendmsg_fexit"`
	TpSchedSchedProcessExit  *ebpf.ProgramSpec `ebpf:"tp_sched_sched_process_exit"`
	UdpRecvmsgFexit          *ebpf.ProgramSpec `ebpf:"udp_recvmsg_fexit"`
	UdpSendmsgFexit          *ebpf.ProgramSpec `ebpf:"udp_sendmsg_fexit"`
	UprobeSSL_read           *ebpf.ProgramSpec `ebpf:"uprobe_SSL_read"`
	UprobeSSL_write          *ebpf.ProgramSpec `ebpf:"uprobe_SSL_write"`
	UretprobeSSL_doHandshake *ebpf.ProgramSpec `ebpf:"uretprobe_SSL_do_handshake"`
	UretprobeSSL_read        *ebpf.ProgramSpec `ebpf:"uretprobe_SSL_read"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	Events        *ebpf.MapSpec `ebpf:"events"`
	SslHandshakes *ebpf.MapSpec `ebpf:"ssl_handshakes"`
	SslReadMap    *ebpf.MapSpec `ebpf:"ssl_read_map"`
	TgidsToTrace  *ebpf.MapSpec `ebpf:"tgids_to_trace"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	Events        *ebpf.Map `ebpf:"events"`
	SslHandshakes *ebpf.Map `ebpf:"ssl_handshakes"`
	SslReadMap    *ebpf.Map `ebpf:"ssl_read_map"`
	TgidsToTrace  *ebpf.Map `ebpf:"tgids_to_trace"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.SslHandshakes,
		m.SslReadMap,
		m.TgidsToTrace,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	TcpRecvmsgFexit          *ebpf.Program `ebpf:"tcp_recvmsg_fexit"`
	TcpSendmsgFexit          *ebpf.Program `ebpf:"tcp_sendmsg_fexit"`
	TpSchedSchedProcessExit  *ebpf.Program `ebpf:"tp_sched_sched_process_exit"`
	UdpRecvmsgFexit          *ebpf.Program `ebpf:"udp_recvmsg_fexit"`
	UdpSendmsgFexit          *ebpf.Program `ebpf:"udp_sendmsg_fexit"`
	UprobeSSL_read           *ebpf.Program `ebpf:"uprobe_SSL_read"`
	UprobeSSL_write          *ebpf.Program `ebpf:"uprobe_SSL_write"`
	UretprobeSSL_doHandshake *ebpf.Program `ebpf:"uretprobe_SSL_do_handshake"`
	UretprobeSSL_read        *ebpf.Program `ebpf:"uretprobe_SSL_read"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.TcpRecvmsgFexit,
		p.TcpSendmsgFexit,
		p.TpSchedSchedProcessExit,
		p.UdpRecvmsgFexit,
		p.UdpSendmsgFexit,
		p.UprobeSSL_read,
		p.UprobeSSL_write,
		p.UretprobeSSL_doHandshake,
		p.UretprobeSSL_read,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
