#ifndef __VORTEX_BPF_H
#define __VORTEX_BPF_H

#define AF_INET  2
#define AF_INET6 10

#define TYPE_FENTRY_SOCK_SENDMSG 1
#define TYPE_FEXIT_SOCK_RECVMSG  2
#define TYPE_FEXIT_TCP_SENDMSG   3
#define TYPE_FEXIT_TCP_RECVMSG   4
#define TYPE_FEXIT_UDP_SENDMSG   5
#define TYPE_FEXIT_UDP_RECVMSG   6
#define TYPE_TP_SYS_ENTER_SENDTO 7
#define TYPE_UPROBE_SSL_WRITE    8
#define TYPE_URETPROBE_SSL_WRITE 9
#define TYPE_UPROBE_SSL_READ     10
#define TYPE_URETPROBE_SSL_READ  11

#define BUF_LEN 256

#define TGID_ENABLE_ALL 0xFFFFFFFF
#define CHUNKED_END_IDX 0xFFFFFFFF

#endif /* __VORTEX_BPF_H */
