#ifndef __VORTEX_H
#define __VORTEX_H

#define AF_INET 2
#define AF_INET6 10

enum {
    TYPE_FENTRY_SOCK_SENDMSG = 1,
    TYPE_FEXIT_SOCK_RECVMSG = 2,
    TYPE_FEXIT_TCP_SENDMSG = 3,
    TYPE_FEXIT_TCP_RECVMSG = 4,
    TYPE_FEXIT_UDP_SENDMSG = 5,
    TYPE_FEXIT_UDP_RECVMSG = 6,
    TYPE_TP_SYS_ENTER_SENDTO = 7,
    TYPE_UPROBE_SSL_WRITE = 8,
    TYPE_URETPROBE_SSL_WRITE = 9,
    TYPE_REPORT_WRITE_SOCKET_INFO = 10,
    TYPE_UPROBE_SSL_READ = 11,
    TYPE_URETPROBE_SSL_READ = 12,
    TYPE_REPORT_READ_SOCKET_INFO = 13,
    TYPE_ANY = 255,
};

#define EVENT_BUF_LEN 256

#define TGID_ENABLE_ALL 0xFFFFFFFF
#define CHUNKED_END_IDX 0xFFFFFFFF

enum {
    VORTEX_NO_TRACE,
    VORTEX_TRACE,
};

enum {
    BPF_CONTINUE_LOOP,
    BPF_END_LOOP,
};

#endif /* __VORTEX_H */
